CREATE TABLE fishspecies (_id integer primary key, name text, description text, baits text, method text, wikilink text);
INSERT INTO fishspecies VALUES(1,"Barbel","Barbus barbus is a species of freshwater fish in the Cyprinidae family of minnows and carps. It shares the common name barbel with its many relatives in the genus Barbus and is properly known as the Common Barbel.","Boilies, Pellets, Worms, Luncheon Meat","Ledger, Bolt Rig, Rolling Pin","http://en.wikipedia.org/wiki/Barbus_barbus");
INSERT INTO fishspecies VALUES(2,"Bleak","Coming Soon","Coming Soon","Coming Soon","http://en.wikipedia.org/wiki/Common_Bleak");
INSERT INTO fishspecies VALUES(3,"Bream","Coming Soon","Coming Soon","Coming Soon","http://en.wikipedia.org/wiki/Bream");
INSERT INTO fishspecies VALUES(4,"Bullhead","Coming Soon","Coming Soon","Coming Soon","http://en.wikipedia.org/wiki/European_bullhead");
INSERT INTO fishspecies VALUES(5,"Carp (Common)","Coming Soon","Coming Soon","Coming Soon","http://en.wikipedia.org/wiki/Common_Carp");
INSERT INTO fishspecies VALUES(6,"Carp (Leather)","Coming Soon","Coming Soon","Coming Soon","http://en.wikipedia.org/wiki/Leather_carp");
INSERT INTO fishspecies VALUES(7,"Carp (Mirror)","Coming Soon","Coming Soon","Coming Soon","http://en.wikipedia.org/wiki/Mirror_Carp");
INSERT INTO fishspecies VALUES(8,"Carp (Wild)","Coming Soon","Coming Soon","Coming Soon","http://en.wikipedia.org/wiki/Common_carp");
INSERT INTO fishspecies VALUES(9,"Chub","Coming Soon","Coming Soon","Coming Soon","http://en.wikipedia.org/wiki/European_chub");
INSERT INTO fishspecies VALUES(10,"Crucian Carp","Coming Soon","Coming Soon","Coming Soon","http://en.wikipedia.org/wiki/Crucian_Carp");
INSERT INTO fishspecies VALUES(11,"Dace","Coming Soon","Coming Soon","Coming Soon","http://en.wikipedia.org/wiki/Leuciscus");
INSERT INTO fishspecies VALUES(12,"Eel","Coming Soon","Coming Soon","Coming Soon","http://en.wikipedia.org/wiki/European_Eel");
INSERT INTO fishspecies VALUES(13,"Grass Carp","Coming Soon","Coming Soon","Coming Soon","http://en.wikipedia.org/wiki/Grass_carp");
INSERT INTO fishspecies VALUES(14,"Gudgeon","Coming Soon","Coming Soon","Coming Soon","http://en.wikipedia.org/wiki/Gudgeon_(fish)");
INSERT INTO fishspecies VALUES(15,"Minnow","Coming Soon","Coming Soon","Coming Soon","http://en.wikipedia.org/wiki/Minnow");
INSERT INTO fishspecies VALUES(16,"Perch","Coming Soon","Coming Soon","Coming Soon","http://en.wikipedia.org/wiki/Perch");
INSERT INTO fishspecies VALUES(17,"Pike","Coming Soon","Coming Soon","Coming Soon","http://en.wikipedia.org/wiki/Esox");
INSERT INTO fishspecies VALUES(18,"Roach","Coming Soon","Coming Soon","Coming Soon","http://en.wikipedia.org/wiki/Common_Roach");
INSERT INTO fishspecies VALUES(19,"Rudd","Coming Soon","Coming Soon","Coming Soon","http://en.wikipedia.org/wiki/Rudd");
INSERT INTO fishspecies VALUES(20,"Ruffe","Coming Soon","Coming Soon","Coming Soon","http://en.wikipedia.org/wiki/Ruffe");
INSERT INTO fishspecies VALUES(21,"Silver Bream","Coming Soon","Coming Soon","Coming Soon","http://en.wikipedia.org/wiki/Silver_Bream");
INSERT INTO fishspecies VALUES(22,"Tench","Coming Soon","Coming Soon","Coming Soon","http://en.wikipedia.org/wiki/Tinca_tinca");
INSERT INTO fishspecies VALUES(23,"Wels Catfish","Coming Soon","Coming Soon","Coming Soon","http://en.wikipedia.org/wiki/Wels_Catfish");
INSERT INTO fishspecies VALUES(24,"Zander","Coming Soon","Coming Soon","Coming Soon","http://en.wikipedia.org/wiki/Zander");
CREATE TABLE fishcaptures (_id integer primary key autoincrement, title text, species integer not null, photo text, pounds integer, ounces integer, drams integer, comment text, FOREIGN KEY(species) REFERENCES fishspecies(_id));
CREATE TABLE fishtargets (_id integer primary key autoincrement, species integer not null, pounds integer, ounces integer, drams integer, FOREIGN KEY(species) REFERENCES fishspecies(_id));